### PR TITLE
Change: (test.js) Use valid z32 encoding in nonexistent URL

### PR DESCRIPTION
**Pull request by josephmturner**
This request should fail, but it doesn't.

### CODE REVIEW

**Comment by RangerMauve** [comment]
This is happening because I haven't added code which throws an error if there's no peers/data found yet.

**Comment by josephmturner** [comment]
I consolidated the invalid URL tests into one, which tests for invalid domains and z32 public keys.

**Comment by RangerMauve** [comment]
Is this still necessary?

**Comment by josephmturner** [comment]
> Is this still necessary?

Yes, I think so.

> This is happening because I haven't added code which throws an error if there's no peers/data found yet.

I think we still want hypercore-fetch to return an error when there are no peers for a hyperdrive, right?

I just tried loading a "fake" valid z32 encoded url with the latest hyper-gateway, and I got ETag 1. Is that expected?

**Comment by josephmturner** [comment]
I rebased off master. Looks like this is still an issue.

**Review by RangerMauve — APPROVED** [review]

**Comment by RangerMauve** [comment]
My only worry is that invalid public keys can be useful for extension messages. But I think I can special case that for the `$/extensions` subpath.

**Pull request merged**
